### ISSUE TITLE
Collect health status of TransportZone

### ISSUE THREAD

**Issue by girikuncoro** [jk8s/nsxt_exporter#30]
NSX golang api client exposes health status transportZone, we have to collect these

**Comment by walbertus** [comment]
Transport zone doesn't have obvious UP/DOWN health status

We can expose these metrics and let PromQL build the query instead:
 - Number of transport node in this zone
 - Number of transport node degraded in this zone
 - Number of transport node down in this zone
 - Number of transport node unknown in this zone
 - Number of transport node up in this zone
