### ISSUE TITLE
Create tests for existing individual collectors

### ISSUE THREAD

**Issue by girikuncoro** [jk8s/nsxt_exporter#36]
Referring to https://github.com/jk8s/nsxt_exporter/blob/master/collector/dhcp_collector_test.go

we need to implement tests for the rest of individual collectors:
- [x] dhcp_collector.go
- [x] logical_port_collector.go
- [x] logical_router_port_collector.go
- [x] logical_switch_collector.go
- [x] system_collector.go
- [x] transport_node_collector.go

**Comment by walbertus** [comment]
Working on logical port and logical router port colector

**Comment by girikuncoro** [comment]
I'm taking the logical_switch_collector_test.go

**Comment by girikuncoro** [comment]
I'm taking system_collector_test.go next

**Comment by walbertus** [comment]
I'm taking the transport node collector test
